### ISSUE TITLE
Seahub "Failed to create thumbnail"

### ISSUE THREAD

**Issue by holantomas** [haiwen/seahub#1658] opened 2017-06-26 07:42 UTC
Hi, I just upgrade seafile to 6.1.1. Install dependencies like ffmpeg(avconv with alias cause Debian) and everything works except video thumbnails.
After load seahub page with video files list, I get ton of "400 Bad Request" (XHR aka AJAX) and content of response is JSON `{"err_msg": "Failed to create thumbnail."}` on url https://seafile.example.com/thumbnail/ff3b2d63-795d-4e2d-ad0b-90cdda0b954d/create/?path=%2FYDXJ0728.mp4&size=48&_=1498462436309 . As you can see it's going for video thumbnail.

**System**
`Linux Vendetta 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux`
**Seafile**
`6.1.1 x64`
**Apache**
`Server version: Apache/2.4.10 (Debian)`

**Comment by shoeper** [comment] 2017-06-26 11:41
Please discuss it in the forum (https://forum.seafile.com). It will be helpful if you include information from the logs (see logs folder within your Seafile install folder).

**Comment by holantomas** [comment] 2017-06-26 11:53
Ok, sorry for that

**Comment by turlando** [comment] 2017-07-17 12:08
I'm facing the same issue after a partially-unsuccessful-but-recovered upgrade from 6.0.x (see #1707 for more details).

The system didn't propose me to install ffmpeg during the upgrade. Is that mandatory for thumbnail generation now?

As a side I would suggest you to avoid pointing users to the forums. I can't tell you how to run your project, but as a user that want to help fixing bug, I can tell it's pretty rude.

Thanks again for the support.

**Comment by shoeper** [comment] 2017-07-17 13:28
> As a side note I would suggest you to avoid pointing users to the forums.

A bug tracker is to keep track of bugs, not installation issues. That's why I point all users where a configuration / setup issue is very likely to the forum.

**Comment by turlando** [comment] 2017-07-17 13:51
>I'm just a community member.

I just said that because I didn't want to start a flame in a bug report. Which eventually happened, it seems :)

>A bug tracker is to keep track of bugs, not installation issues.

Totally agree. But:
1. More than one person is affected by the very same issue
2. It seems to be an upgrade problem, so there could something wrong with the code

I see, nobody is doing support (for the specific installation). But if something gets broken after an upgrade, and if the user followed the documentation, well, I, as developer, I should start thinking that maybe there could be something in my code, right?

>Looks like it got to easy to open issues with Github.

If it's not a bug just let the devs close the issue then :)

**Comment by turlando** [comment] 2017-07-21 00:04
Follow up: upgrading from 6.1.4 to 6.1.5 did not solve the issue.

How do we make sure the developers are looking at this?

**Comment by manches** [comment] 2017-10-29 20:38
I had the same problem and I resolved it.
My problem was the version of Pillow.
You can see the version you need on the doc:
         seafile-server-latest/seahub/requirements.txt 

To solve this just do:

- Check the version: pip show Pillow
- Uninstall the actual version: pip uninstall  Pillow
- Install a compatibile version: pip install Pillow==2.6.1

**Closed** 2018-05-29 17:29 UTC
