### ISSUE TITLE
500 Internal Server Error when accesing files/history via Seahub

### ISSUE THREAD

**Issue by devillemereuil** [haiwen/seahub#305] opened 2014-11-18 14:04 UTC
Since a few versions (around 3.1.X), when accessing the history via Seahub on my private Seafile server, I encounter a "500 Internal server error". No change have been made on the Apache configuration since the "old" days of 3.0.

Some times, when trying hard, I can temporarily access the history/viewing the files, but eventually I'll go back to the 500 Internal Error issue.

Library is encrypted if that matters.

**Comment by freeplant** [comment] 2015-01-28 14:07
The problem is solved and will be included in the next release.

**Comment by chatainsim** [comment] 2015-02-03 10:18
Thanks for the fix !
What's causing this issue ?

**Comment by freeplant** [comment] 2015-02-07 15:11
Here is the list of slow problems:

1. View a file is slow. (solved as in #302 by remove the calculation of contributors)
2. View trash is slow. (solved in version 4.0.6 server by using a new algorithm) 
3. View file's history page is slow if the library is modified frequently. (not solved yet).

**Comment by shoeper** [comment] 2015-02-07 15:16
Maybe some caching using memcached or MySQL could help.

**Closed** 2016-11-26 08:44 UTC
