### ISSUE TITLE
Failed to get total storage occupation

### ISSUE THREAD

**Issue by kusmierz** [haiwen/seahub#5954] opened 2024-02-13 17:27 UTC
it seems my instance of seafile 11.0.5 doesn't count total storage usage, it shows 0 every day, but I enabled it few days ago. In `logs/seafevents.log` log file I have got:
```log
[2024-02-13 18:16:08,490] [INFO] Start counting total storage..
[2024-02-13 18:16:08,494] [WARNING] [TotalStorageCounter] Failed to get total storage occupation: OrgRepo
```
How to fix it?

I'm not sure if it's connected, but in `logs/seafile-monitor.log` I have:
```log
/opt/seafile/seafile-server-11.0.5/pro/python/seafevents/statistics/counter.py:289: SAWarning: SELECT statement has a cartesian product between FROM element(s) "UserTraffic" and FROM element "SysTraffic".  Apply join condition(s) between each element to resolve.
  self.edb_session.execute(stmt)
```

**Comment by jie-seafile** [comment] 2024-02-20 02:41
Local testing could not reproduce the problem

**Comment by kusmierz** [comment] 2024-02-20 06:47
How can I send you more debug info? What would be helpful?

**Comment by freeplant** [comment] 2024-03-23 08:22
This is a bug. The fix will be included in the next release.

**Closed by freeplant** 2024-03-23 08:22 UTC
Labels: bug
