### ISSUE TITLE
Directory listing is slow for large folders

### ISSUE THREAD

**Issue by allo-** [haiwen/seahub#323] opened 2014-12-25 00:21 UTC
When a folder contains many (thousands) files, then the listing via seahub is very slow and the lazy loading when scrolling to the bottom makes it hard to find a file.
There should be some kind of cache for the filelist (no previews or other stuff needed) or something similiar.

**Comment by freeplant** [comment] 2015-08-22 05:53
Can't reproduce the problem.

**Comment by allo-** [comment] 2015-08-22 09:58
Re-Tested it, problem still exists.

- The Lazy Loading of the filelist is a problem, because it breaks Ctrl-F. There are no filters or search-boxes to replace the functionality
- Scrolling is slow in the sense, that you scroll down to the bottom (fastest: hit the "End" key), then wait half an second for the list to grow, then hit "End" again, wait again, scroll again, and so on. On a large file list, you will need to do this many times before you get to see the last file.

Problem should be reproducible by syncing a folder with empty files "1" to "20000" and then trying to scroll to number 20000 in the listing.

**Comment by allo-** [comment] 2015-08-23 17:41
Problem still exists with 4.3.2

**Comment by freeplant** [comment] 2015-08-24 02:13
I get want you mean now. How many files do you have in the your large directory in practical?

**Comment by allo-** [comment] 2015-08-24 17:09
This is actually around 20000, small files. Text and Images and some subfolders.

Its not too annoying, as i mostly use the synced version, but when i try to find one file in the webinterface, there is no chance.

On the other hand, load such a large list will propably not have good performance in the browser either, so some textbox which filters the list on the fly would be an option. Or an switch between endless scroll and pagination.

**Comment by allo-** [comment] 2015-09-10 16:13
By the way: On the snapshot page, you get the whole list without the lazy-loading. Which creates a huge load time and much cpu usage in the same folder.

So the solution should be some kind of filtering, not showing all files on one page.
And the snapshot-page propably should do it the same way as the normal folder view.

**Comment by shoeper** [comment] 2015-09-10 16:44
Currently I could also think of a dos attack. A user could add and remove many files to a library and then access the snapshot page with a param to show 10000 results at once. Doing this multiple times at once leads to very high server load (and could possibly lead to outages).

**Comment by allo-** [comment] 2015-09-10 16:56
The snapshots-list page is not (this) problem. But you have for every snapshot a "view snapshot" page, which shows all files, which exist in the snapshot, not only the new/deleted ones.
And this might be a DoS. I did not look how much cpu seafile took on the server side.

**Comment by freeplant** [comment] 2016-10-31 08:16
This problem is fixed in the latest version.

**Closed by freeplant** 2016-10-31 08:16 UTC
